baseURL = 'https://kyuwonweon.github.io/'
languageCode = 'en-us'
title = 'Q1 Portfolio'
theme = 'PaperMod'

[params]
    defaultTheme = "dark"
    description = "Robotics Engineer | MS in Robotics Student | ROS 2"
    ShowReadingTime = false
    ShowShareButtons = false
    disableSpecial1stPost = true
    mainSections = ["projects"]

    [params.homeInfoParams]
      Title = "Kyuwon Weon"
      Content = """
  **MS IN ROBOTICS @NORTHWESTERN**

  **BS IN MECHE AND BME @CARNEGIE MELLON UNIVERSITY**

  Bridging industrial mechanical design experience with robotic software stack
  """
    [[params.socialIcons]]
        name = "github"
        url = "https://github.com/kyuwonweon"

    [[params.socialIcons]]
        name = "linkedin"
        url = "https://linkedin.com/in/kyuwon-weon-a6bb2a213"

    [[params.socialIcons]]
        name = "email"
        url = "mailto:kyuwon0917@gmail.com"

[menu]
    [[menu.main]]
        identifier = "projects"
        name = "Projects"
        url = "/projects/"
        weight = 10
    [[menu.main]]
        identifier = "resume"
        name = "Resume"
        url = "/resume.pdf"
        weight = 20
    [[menu.main]]
        identifier = "about"
        name = "About"
        url = "/about"
        weight = 30
    [[menu.main]]
        identifier = "contact"
        name = "Contact"
        url = "/contact"
        weight = 40
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['\[', '\]'], ['$$', '$$']]
          inline = [['\(', '\)'], ['$', '$']]